type BaseChannel {
    id: String!
    name: String!
    messages: [Message]!
    type: String!
    createdAt: DateTime!
    createdTimestamp: Timestamp!
    updatedAt: DateTime!
    updatedTimestamp: Timestamp!
}

type BaseServerChannel @inherits(type: "BaseChannel") {
    server: Server!
    position: Int!
}

type TextChannel @inherits(type: "BaseServerChannel") {
    category: CategoryChannel!
    topic: String
    nsfw: Boolean!
}

type DMChannel @inherits(type: "BaseChannel") {
    recipient1: User!
    recipient2: User!
}

type VoiceChannel @inherits(type: "BaseServerChannel") {
    category: CategoryChannel!
}

type CategoryChannel @inherits(type: "BaseServerChannel") {
    children: [CategoryChildChannel]!
}

union CategoryChildChannel = TextChannel | VoiceChannel

union ServerChannel = CategoryChannel | TextChannel | VoiceChannel
union Channel = CategoryChannel | TextChannel | VoiceChannel | DMChannel

extend type Query {
    getTextChannel(serverId: String!, id: String!): TextChannel!
    getTextChannels(serverId: String!): [TextChannel]!

    getVoiceChannel(serverId: String!, id: String!): VoiceChannel!
    getVoiceChannels(serverId: String!): [VoiceChannel]!

    getCategoryChannel(serverId: String!, id: String!): CategoryChannel!
    getCategoryChannels(serverId: String!): [CategoryChannel]!

    getChannel(serverId: String!, id: String!): ServerChannel!
    getChannels(serverId: String!, type: [String]): [ServerChannel]!
}

extend type Mutation {
    createChannel(
        serverId: String!
        name: String!
        type: String!
    ): ServerChannel!
    deleteChannel(serverId: String!, id: String!): ServerChannel!
    updateChannel(
        serverId: String!
        id: String!
        propertyNames: [String!]!
        propertyValues: [Any!]!
    ): ServerChannel!
}

extend type Subscription {
    channelCreated(serverId: String!): ServerChannel!
    channelDeleted(serverId: String!): ServerChannel!
}
