type FriendChannel {
    id: String!
    participants: [User]!
    messages: [Message]!
    createdAt: DateTime!
    createdTimestamp: Timestamp!
    updatedAt: DateTime!
    updatedTimestamp: Timestamp!
}

type Query {
    getFriends: [User]!
    getFriendChannels: [FriendChannel]!
}

type Mutation {
    sendFriendRequest(userId: String!): Boolean!
    acceptFriendRequest(userId: String!): User!
    declineFriendRequest(userId: String!): User!
    removeFriend(userId: String!): User!
}
