type Message {
    id: String!
    content: String!
    edited: Boolean!
    author: User!
    embeds: [MessageEmbed]!
    attachments: [MessageAttachment]!
    channel: Channel!
    member: Member!
    server: Server!
    createdAt: DateTime!
    createdTimestamp: Timestamp!
    updatedAt: DateTime!
    updatedTimestamp: Timestamp!
}

type MessageEmbed {
    title: String
    description: String
    url: String
    color: String
    timestamp: Timestamp
    author: EmbedAuthor
    footer: EmbedFooter
    image: String
    media: String
}

type MessageAttachment {
    url: String!
    filename: String!
    size: Int!
    contentType: String!
}

type EmbedAuthor {
    name: String!
    url: String
    iconUrl: String
}

type EmbedFooter {
    text: String!
    iconUrl: String
}

extend type Query {
    getMessage(serverId: String!, channelId: String!, id: String!): Message!
    getMessages(serverId: String!, channelId: String!, $limit: Int, $cursor: String): [Message]!
}

extend type Mutation {
    createMessage(
        serverId: String!
        channelId: String!
        content: String!
    ): Message!
    deleteMessage(serverId: String!, channelId: String!, id: String!): Message!
    editMessage(
        serverId: String!
        channelId: String!
        id: String!
        content: String!
    ): Message!
}

extend type Subscription {
    messageCreated(serverId: String!, channelId: String!): Message!
    messageEdited(serverId: String!, channelId: String!): Message!
    messageDeleted(serverId: String!, channelId: String!): Message!
}
